name: Notify
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  integration_test_incoming_webhook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: echo "${{ github.event_name }}"
    - name: Notify slack on pull request
      if: ${{ github.event_name == 'pull_request' }}
      id: slackIncomingPR
      uses: ./
      with:
        payload: "{\"text\":\"New pull request on repository ${{ github.repository }}: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }}\"}"
      env:
        SLACK_WEBHOOK_URL: ${{ vars.SLACK_INCOMING_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    - name: Notify slack on issue
      if: ${{ github.event_name == 'issues' }}
      id: slackIncomingIssue
      uses: ./
      with:
        payload: "{\"text\":\"New issue on repository ${{ github.repository }}: ${{ github.server_url }}/${{ github.repository }}/issues/${{ github.event.number }}\"}"
      env:
        SLACK_WEBHOOK_URL: ${{ vars.SLACK_INCOMING_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
